---
- name: Desplegar entorn de pentesting per a Quantum Breach
  hosts: localhost
  connection: local
  become: yes

  vars:
    exposed_port: 8081
    project_dir: "/home/ubuntu/quantum_breach"
    maquina_nombre: "Quantum Breach"
    flag_prefix: "SH4D0WB0X_"
    secret_flag: "{{ flag_prefix }}{{ 1000 | random | to_uuid }}"

  pre_tasks:
    - name: Verificar si Ansible té community.postgresql
      command: ansible-galaxy collection list community.postgresql
      register: check_pg_collection
      ignore_errors: yes
      changed_when: false

    - name: Instal·lar community.postgresql si cal
      command: ansible-galaxy collection install community.postgresql
      when: check_pg_collection.rc != 0

  tasks:
    - name: Generar flag dinàmica
      set_fact:
        secret_flag: "{{ flag_prefix }}{{ 1000 | random | to_uuid }}"

    - name: Sobreescriure flag.txt amb flag nova
      copy:
        dest: "{{ project_dir }}/www/flag.txt"
        content: "{{ secret_flag }}"
        mode: '0644'

    - name: Detenir contenidors anteriors
      command: docker compose -f {{ project_dir }}/docker/docker-compose.yml down -v
      ignore_errors: yes
      changed_when: false

    - name: Construir i desplegar contenidors
      command: docker compose -f {{ project_dir }}/docker/docker-compose.yml up -d --build
      args:
        chdir: "{{ project_dir }}/docker"

    - name: Esperar inici del servei web
      wait_for:
        host: localhost
        port: "{{ exposed_port }}"
        timeout: 30

    - name: Guardar credencials i info
      copy:
        dest: "{{ project_dir }}/credentials.txt"
        content: |
          🧪 Màquina: {{ maquina_nombre }}
          🌐 URL: http://localhost:{{ exposed_port }}
          🏁 Flag: {{ secret_flag }}

          🔓 Vector: Injecció de Comandes
          Ex: 127.0.0.1; cat flag.txt
        mode: '0600'

    - name: Inserir flag a Neon
      community.postgresql.postgresql_query:
        db: shadows
        login_user: shadows_owner
        login_password: npg_NMFyn6QGR5re
        login_host: ep-dark-credit-a2jn9u2r-pooler.eu-central-1.aws.neon.tech
        port: 5432
        ssl_mode: require
        query: |
          UPDATE maquinas
          SET respuesta = '{{ secret_flag }}'
          WHERE nombre = '{{ maquina_nombre }}';

    - name: Mostrar resum final
      debug:
        msg: |
          ✅ Quantum Breach desplegada correctament
          URL: http://localhost:{{ exposed_port }}
          FLAG: {{ secret_flag }}
