version: "3.9"

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: vulnerable_webapp
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ../www:/var/www/html
    networks:
      - shadow_net
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    container_name: vulnerable_db
    environment:
      POSTGRES_PASSWORD: ShadowBox123!
      POSTGRES_DB: shadow_db
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../db_init:/docker-entrypoint-initdb.d
    networks:
      - shadow_net
    restart: unless-stopped

volumes:
  pg_data:

networks:
  shadow_net:
    driver: bridge
